# Generated by Django 5.1.7 on 2025-03-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
