# Generated by Django 5.1.7 on 2025-03-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsite', '0002_partenaire_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='TypePartenaire',
        ),
        migrations.RenameField(
            model_name='partenaire',
            old_name='categorie',
            new_name='type_partenaire',
        ),
    ]
