# Generated by Django 5.1.7 on 2025-03-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsite', '0003_rename_categorie_typepartenaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(choices=[('billetterie', 'Billetterie'), ('programmation', 'Programmation'), ('partenariat', 'Partenariat'), ('presse', 'Presse'), ('autre', 'Autre')], max_length=20)),
                ('message', models.TextField()),
                ('date_envoye', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
