# Generated by Django 5.1.7 on 2025-03-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsite', '0004_messagecontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagecontact',
            old_name='date_envoye',
            new_name='date_creation',
        ),
        migrations.AddField(
            model_name='messagecontact',
            name='reponse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='sujet',
            field=models.CharField(max_length=100),
        ),
    ]
